# GoReleaser configuration for c64u
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: c64u
    main: ./cmd/c64u
    binary: c64u
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: c64u
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - RELEASE.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: cybersorcerer
    name: c64.nvim
  draft: false
  prerelease: auto
  name_template: "c64u {{.Version}}"
  header: |
    ## C64 Ultimate CLI Tool - {{.Version}}

    Command-line interface for the C64 Ultimate hardware.
